### Test route
GET http://localhost:3000/

### Get all products
GET http://localhost:3000/products

### Get product by id
GET http://localhost:3000/products/2

### Get product by id >> "Product not found"
GET http://localhost:3000/products/999


### Create/add new product
POST http://localhost:3000/products 
Content-Type: application/json

{
    "productName": "New Prototype Soap",
    "price": 999,
    "quantity": 5
}

### Update the product
PUT http://localhost:3000/products/2
Content-Type: application/json

{
    "productName": "Classic Soap",
    "price": 89
}

### Edit a product
PATCH http://localhost:3000/products/1 
Content-Type: application/json

{
    "price": 89
}

### Delete a product
DELETE http://localhost:3000/products/3
